title: amniskin
email: aaron@niskin.org
author: amniskin
twitter:
  card: summary
  username: amniskin

exclude:
  - amniskin-blog-gem.gemspec
  - LICENSE.txt

# logo: "/favicon.ico"
avatarurl: "https://secure.gravatar.com/avatar/5267e8bc17bebc6f6e39eab09457eeb5"
social: # jekyll-seo-tag > social overrides
  name: Aaron Niskin # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/amniskin
    - https://www.linkedin.com/in/aaron-niskin
    - https://plus.google.com/+AaronNiskin
    - https://github.com/amniskin

social_links:
  Twitter: https://twitter.com/amniskin
  LinkedIn: https://www.linkedin.com/in/aaron-niskin
  GitHub: https://github.com/amniskin

copyright: Copyright © 2008-2025
tagline: Aaron Niskin's personal blog
description: >- # this means to ignore newlines until "baseurl:"
  Home of a MathemaNiskin.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aaron.niskin.org"
# favicon: "/favicon.ico"
favicon: "https://secure.gravatar.com/avatar/5267e8bc17bebc6f6e39eab09457eeb5"

# debug: false

google_analytics: "UA-67291006-1"
enableDNT: "false"
sitemap: true
lang: "en"

# langs refer to https://cloud.google.com/translate/docs/languages
translate_langs:
  - lang: en
    img: https://www.countryflags.io/us/flat/64.png
    text: English
  - lang: es
    img: https://www.countryflags.io/es/flat/64.png
    text: Spanish
  - lang: iw
    img: https://www.countryflags.io/il/flat/64.png
    text: Hebrew
  - lang: fr
    img: https://www.countryflags.io/fr/flat/64.png
    text: French
  - lang: zh-CN
    img: https://www.countryflags.io/cn/flat/64.png
    text: Chinese(Simple)
  - lang: zh-TW
    img: https://www.countryflags.io/tw/flat/64.png
    text: Chinese(Traditional)
  - lang: ja
    img: https://www.countryflags.io/jp/flat/64.png
    text: Japanese
  - lang: ko
    img: https://www.countryflags.io/kr/flat/64.png
    text: Korean
  - lang: ru
    img: https://www.countryflags.io/ru/flat/64.png
    text: Russian

# spacegrey: #353535
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
yat:
  date_format: "%a, %b %d, %Y"
header_transparent: true
theme_color: "#353535"
night_mode: "on"

# Code badge setting
# You can enable or disable the code badge and so on
code_badge:
  enabled: "true"
  color: "#353535"
  background_color: "#00B3FF"
  text_transform: "uppercase"  # ("uppercase", "lowercase", "capitalize")

header_pages:
  - resume.md
  - archives.md
  - categories.md
  - tags.md

# Page default value
# defaults:
#   home:
#     heading: "Your awesome heading"
#     subheading: "Your awesome subheading"
#     banner: "Your image url"

# Pagination setting
paginate: 10

# Disqus comments
disqus:
  shortname: "aaron-niskin-org"

# Gitment comments
# gitment:
#   username: "Your GitHub username"
#   repo: "The repo to store comments"
#   client_id: "Your client ID"
#   client_secret: "Your client secret"
#   redirect_uri: "Your redirect url"   # If you use a custom domain name

# Build settings
# highlighter: none
show_drafts: true
markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-mentions
