title: amniskin
email: aaron@niskin.org
author: amniskin
twitter:
  card: summary
  username: amniskin

# logo: "/favicon.ico"
avatarurl: "https://secure.gravatar.com/avatar/5267e8bc17bebc6f6e39eab09457eeb5"
social: # jekyll-seo-tag > social overrides
  name: Aaron Niskin # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/amniskin
    - https://www.linkedin.com/in/aaron-niskin
    - https://plus.google.com/+AaronNiskin
    - https://github.com/amniskin

social_links:
  Twitter: https://twitter.com/amniskin
  LinkedIn: https://www.linkedin.com/in/aaron-niskin
  GitHub: https://github.com/amniskin

copyright: Copyright © 2008-2021
tagline: Aaron Niskin's personal blog
description: >- # this means to ignore newlines until "baseurl:"
  Home of a MathemaNiskin. This is a place for me to rant about whatever I feel
  like ranting about. Hopefully more math and fun than otherwise.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aaron.niskin.org"
# favicon: "/favicon.ico"
favicon: "https://secure.gravatar.com/avatar/5267e8bc17bebc6f6e39eab09457eeb5"

# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
yat:
  date_format: "%a, %b %d, %Y"

# debug: false

header_transparent: true

google_analytics: "UA-67291006-1"
enableDNT: "false"
sitemap: true
lang: "en"

# langs refer to https://cloud.google.com/translate/docs/languages
translate_langs:
  - lang: en
    img: https://www.countryflags.io/us/flat/64.png
    text: English
  - lang: es
    img: https://www.countryflags.io/es/flat/64.png
    text: Spanish
  - lang: iw
    img: https://www.countryflags.io/il/flat/64.png
    text: Hebrew
  - lang: fr
    img: https://www.countryflags.io/fr/flat/64.png
    text: French
  - lang: zh-CN
    img: https://www.countryflags.io/cn/flat/64.png
    text: Chinese(Simple)
  - lang: zh-TW
    img: https://www.countryflags.io/tw/flat/64.png
    text: Chinese(Traditional)
  - lang: ja
    img: https://www.countryflags.io/jp/flat/64.png
    text: Japanese
  - lang: ko
    img: https://www.countryflags.io/kr/flat/64.png
    text: Korean
  - lang: ru
    img: https://www.countryflags.io/ru/flat/64.png
    text: Russian

# You can choose a theme color
# Default theme colors as below:
# coolblack: #090a0b
# spacegrey: #353535
# snowwhite: #ffffff
#
# theme_color: snowwhite
theme_color: spacegrey
#
# Custom color as below:
# theme_color: "#882250"

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is"manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
#
# night_mode: "auto"
night_mode: "on"

# Code badge setting
# You can enable or disable the code badge and so on
code_badge:
  enabled: "true"
  color: "#353535"
  background_color: "#ff4e00"
  text_transform: "uppercase"  # ("uppercase", "lowercase", "capitalize")

header_pages:
  - about.html
  - archives.html
  - categories.html
  - tags.html

# Page default value
# defaults:
#   home:
#     heading: "Your awesome heading"
#     subheading: "Your awesome subheading"
#     banner: "Your image url"

# Pagination setting
paginate: 10

# Disqus comments
disqus:
  shortname: "aaron-niskin-org"

# Gitment comments
# gitment:
#   username: "Your GitHub username"
#   repo: "The repo to store comments"
#   client_id: "Your client ID"
#   client_secret: "Your client secret"
#   redirect_uri: "Your redirect url"   # If you use a custom domain name

# Build settings
# highlighter: none
markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship

jekyll-spaceship:
  # default enabled processors
  processors:
    - table-processor
    - mathjax-processor
    - plantuml-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor
  mathjax-processor:
    src:
      - https://polyfill.io/v3/polyfill.min.js?features=es6
        # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js
    config:
      tex2jax:
        inlineMath:
          - ['$','$']
        displayMath:
          - ['$$','$$']
      svg:
        fontCache: 'global'
    optimize: # optimization on building stage to check and add mathjax scripts
      enabled: true # value `false` for adding to all pages
      include: []   # include patterns for math expressions checking (regexp)
      exclude: []   # exclude patterns for math expressions checking (regexp)
  plantuml-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: plantuml
    syntax:
      code: 'plantuml!'
      custom: ['@startuml', '@enduml']
    src: http://www.plantuml.com/plantuml/svg/
  mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: 'mermaid!'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
    src: https://mermaid.ink/svg/
  media-processor:
    default:
      id: 'media-{id}'
      class: 'media'
      width: '100%'
      height: 350
      frameborder: 0
      style: 'max-width: 600px; outline: none;'
      allow: 'encrypted-media; picture-in-picture'
  emoji-processor:
    css:
      class: emoji
    src: https://github.githubassets.com/images/icons/emoji/
