#!/usr/bin/env python3
import os
import sys

_BASE_DIR = os.path.abspath(os.path.join(__file__, '..', '..'))
DRAFTS_DIR = os.path.join(_BASE_DIR, '_drafts')
POSTS_DIR = os.path.join(_BASE_DIR, '_posts')


def draft():
    post_name = ' '.join(sys.argv[1:])
    print(post_name)
    """
    post_name = input("Please enter the name of your post (spaces will be "
                      "replaced with slashes):")
    """
    slugged = post_name.replace(' ', '-')
    with open(os.path.join(DRAFTS_DIR, slugged + '.md'), 'w') as f:
        f.write('---\n')
        f.write('layout: post\n')
        f.write('title: ' + post_name + '\n')
        f.write('description:\n')
        f.write('category:\n')
        f.write('tags:\n')
        f.write('---\n')


if __name__ == '__main__':
    draft()
