// Compiled by ClojureScript 1.7.48 {:static-fns true, :optimize-constants true}
goog.provide('tailrecursion.hoplon.app_pages._index_DOT_html');
goog.require('cljs.core');
goog.require('content.home.subjects');
goog.require('content.home.highlights');
goog.require('content.home.contact');
goog.require('content.home.um');
goog.require('general.navbar');
goog.require('content.home.fiu');
goog.require('tailrecursion.hoplon');
goog.require('tailrecursion.javelin');
goog.require('general.sections');
goog.require('general.head');
goog.require('content.home.top');
goog.require('general.footer');
goog.require('content.home.testimonials');
tailrecursion.hoplon.html.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.cst$kw$lang,"en",(function (){var G__9658 = (tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1("Home of a Mathema-Niskin!") : tailrecursion.hoplon.title.call(null,"Home of a Mathema-Niskin!"));
var G__9659 = general.head.viewport();
var G__9660 = general.head.bootstrap();
return (tailrecursion.hoplon.head.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.head.cljs$core$IFn$_invoke$arity$3(G__9658,G__9659,G__9660) : tailrecursion.hoplon.head.call(null,G__9658,G__9659,G__9660));
})(),(function (){var G__9661 = general.navbar.fixed();
var G__9662 = (function (){var G__9663 = cljs.core.cst$kw$class;
var G__9664 = "fade-bg";
var G__9665 = content.home.top.content();
var G__9666 = content.home.subjects.content();
var G__9667 = general.sections.divider();
var G__9668 = content.home.fiu.content();
var G__9669 = general.sections.divider();
var G__9670 = content.home.testimonials.content();
var G__9671 = general.sections.divider();
var G__9672 = content.home.um.content();
var G__9673 = general.sections.divider();
var G__9674 = content.home.contact.content();
var G__9675 = general.footer.content();
return (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$13 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$13(G__9663,G__9664,G__9665,G__9666,G__9667,G__9668,G__9669,G__9670,G__9671,G__9672,G__9673,G__9674,G__9675) : tailrecursion.hoplon.div.call(null,G__9663,G__9664,G__9665,G__9666,G__9667,G__9668,G__9669,G__9670,G__9671,G__9672,G__9673,G__9674,G__9675));
})();
return (tailrecursion.hoplon.body.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.body.cljs$core$IFn$_invoke$arity$2(G__9661,G__9662) : tailrecursion.hoplon.body.call(null,G__9661,G__9662));
})()], 0));
