// Compiled by ClojureScript 1.7.48 {:static-fns true, :optimize-constants true}
goog.provide('tailrecursion.hoplon.app_pages._book_SLASH_sicp_SLASH_index_DOT_html');
goog.require('cljs.core');
goog.require('book.sicp.texts.ch1sect2');
goog.require('book.sicp.texts.about');
goog.require('book.sicp.texts.ch2sect2');
goog.require('general.navbar');
goog.require('book.sicp.texts.ch2sect3');
goog.require('book.sicp.book_data');
goog.require('tailrecursion.hoplon');
goog.require('book.sicp.texts.ch1');
goog.require('book.sicp.texts.ch2');
goog.require('tailrecursion.javelin');
goog.require('book.sicp.texts.ch1sect1');
goog.require('general.sections');
goog.require('general.head');
goog.require('general.bootstrap');
goog.require('general.footer');
goog.require('book.sicp.texts.ch1sect3');
goog.require('book.sicp.texts.ch2sect1');
tailrecursion.hoplon.html.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([(function (){var G__180091 = (tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1("SICP... Now in Clojure!") : tailrecursion.hoplon.title.call(null,"SICP... Now in Clojure!"));
var G__180092 = general.head.bootstrap();
var G__180093 = general.head.viewport();
var G__180094 = general.head.google_analytics();
var G__180095 = general.head.mathjax();
return (tailrecursion.hoplon.head.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.head.cljs$core$IFn$_invoke$arity$5(G__180091,G__180092,G__180093,G__180094,G__180095) : tailrecursion.hoplon.head.call(null,G__180091,G__180092,G__180093,G__180094,G__180095));
})(),(function (){var G__180096 = general.navbar.fixed();
var G__180097 = general.bootstrap.container.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([general.sections.sidebar.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([book.sicp.book_data.toc()], 0)),general.sections.content_with_sidebar.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([book.sicp.book_data.content.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([book.sicp.texts.about.content(),book.sicp.texts.ch1.content(),book.sicp.texts.ch1sect1.content(),book.sicp.texts.ch1sect2.content(),book.sicp.texts.ch1sect3.content(),book.sicp.texts.ch2.content(),book.sicp.texts.ch2sect1.content(),book.sicp.texts.ch2sect2.content(),book.sicp.texts.ch2sect3.content(),general.footer.content()], 0))], 0))], 0));
return (tailrecursion.hoplon.body.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.body.cljs$core$IFn$_invoke$arity$2(G__180096,G__180097) : tailrecursion.hoplon.body.call(null,G__180096,G__180097));
})()], 0));
